---
apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  namespace: kafka
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kafka
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30092

---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-nodeport
  namespace: flink
spec:
  type: NodePort
  selector:
    app: my-flink-session
    component: jobmanager
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
