apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/kraft: "enabled"
    strimzi.io/node-pools: "enabled"
spec:
  kafka:
    version: 4.0.0
    config:
      auto.create.topics.enable: "true"
      default.replication.factor: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      min.insync.replicas: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false      
      - name: external
        port: 9094
        type: nodeport   # 或者 LoadBalancer（推荐 cloud 环境）
        tls: false
        configuration:
          bootstrap:
            nodePort: 30092  # 你可以自定义端口
          brokers:
            - broker: 0
              nodePort: 30093
  entityOperator:
    topicOperator: {}
    userOperator: {}